### ISSUE TITLE
John Wiedenmann bug report:

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#102]
I was going through and looking at the function that calculates Z using the catch curve function (CC). The issue is that ny is supposed to be the number of years, but it it based on the number of columns.  Then the next line that defines the subsetted CAA (which I think you’re trying to do the last 3 years) uses the ny as a row index.  So instead of accessing the last 3 years of the matrix, it’s accessing the years corresponding to the highest ages. Am I interpreting this right?

TC: My bet is that John is right!

**Comment by AdrianHordyk** [comment]
`Data@CAA` is a 3D array - dimensions nsim, nyears, maxage (or less). `ny <- dim(Data@CAA)[2]` is correct for counting number of years.
