### ISSUE TITLE
Errors when proyears = 1 or 2 and interval =1 or 2

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#131]
# Eg:

test1<-test2<-test3<-test4<-testOM

test1@proyears<-1
test1@interval<-1
runMSE(test1)

test2@proyears<-2
test2@interval<-1
runMSE(test2)

test3@proyears<-1
test3@interval<-2
runMSE(test3)

**Comment by AdrianHordyk** [comment]
Added error message if proyears < 2
Issue with interval = 1 has been fixed
