### ISSUE TITLE
MSE@OM@LFC is recorded as discrete and shouldn't be - causes issues for VOI etc

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#134]
myOM<-makePerf(new('OM',Snapper,Generic_Fleet,Perfect_Info,Perfect_Imp))
myOM@nsim<-200
myOM@M<-c(0.2,0.2)
myOM@Size_area_1<-c(0.2,0.2)
myOM@Frac_area_1<-c(0.2,0.2)
myOM@Prob_staying<-c(0.95,0.95)
myOM@proyears<-50
myOM@interval<-4
myOM@D<-c(0.05,0.45)
MSEobj<-runMSE(myOM)

# see this:
MSEobj@OM$LFC

**Comment by AdrianHordyk** [comment]
Fixed
