### ISSUE TITLE
Scale dependent stability and running time with OM@R0 slot

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#145]
e.g:

system.time({
  testOM@R0<-100000
  out<-runMSE(testOM,Hist=T)
})

system.time({
  testOM@R0<-100
  out<-runMSE(testOM,Hist=T)
})

should be scale-independent

**Comment by AdrianHordyk** [comment]
possibly caused when generating length comp - todo: fix R0 and re-scale at end
