### ISSUE TITLE
Fdem function generates values of steepness above 1

### ISSUE THREAD

**Issue by AdrianHordyk** [DLMtool/DLMtool#16]

**Comment by quang-huynh** [comment]
To generate steepness values, a random variable X ~ Beta(a, b) can be sampled and then transformed (H = 0.8 X + 0.2) so that values are between 0.2 - 1.0. Parameters a and b of r.v. X can be calculated to correspond to the mean and CV of H.

**Comment by AdrianHordyk** [comment]
replaced all samples of h from trlnorm to Quang's function: sample_steepness2
