### ISSUE TITLE
Warning msn

### ISSUE THREAD

**Issue by MauroMardones** [DLMtool/DLMtool#214]
i don't know if this is a bug or just my own error;

Warning in optimize(optQ, log(bounds), depc = D[x], SSB0c = SSB0[x], nareas,  :
  NA/Inf replaced by maximum positive value
16 sims can't get down to the lower bound on depletion
3 sims can't get to the upper bound on depletion
Error in runMSE_int(OM, MPs, CheckMPs, timelimit, Hist, ntrials, fracD,  : 
  Change OM@seed and try again for a complete new sample, modify the input parameters, or increase ntrials

You can help me? I've been in this traffic jam for two days!
appreciate

**Comment by AdrianHordyk** [comment]
The warning message of NA/Inf suggests that there may be missing or incorrect values in the OM. 

A few things to check:
- are OM@h values > 0.2 & < 1?
- are selectivity parameters in absolute units - eg mm? If so, make sure that OM@isRel <- 'FALSE'
- maturity and selectivity parameters are > 0 and < Linf?

If none of these, it may be some other problem with OM or with code. Possible to send me the OM?

**Comment by MauroMardones** [comment]
I have corroborated what you tell me and the problem continues.
Of course I can send the OM to help me.

[MyOM.xlsx](https://github.com/DLMtool/DLMtool/files/2291992/MyOM.xlsx)

Greetings from Chile, but now I'm working with Ray Hilborn in Seattle, and I want to implement MSE with DLMTool for benthic fisheries in Chile

**Comment by AdrianHordyk** [comment]
There are a couple of problems with the OM. Note that the 1st and 2nd values in the OM slots are lower and upper bounds from a uniform distribution. There are ways to include other distributions, but this is done outside of Excel (see the Custom Parameters section in the user-guide [`userguide()`]. 

For example, Linf is currently 138 and 0.2, but is expecting lower and upper bounds. Similiar with depletion (D) which is currently 0.5 and 0.25. This represents a uniform distribution between 0.25 and 0.5. Standard convention is lower bound in column B and upper in column C.

A few other things:
- size_area_1, frac_area_1, and prob_staying must be > 0 & < 1
- Vmaxlen and Rmaxlen are values between 0 and 1 (vulnerability of fish at Linf)
- selectivity parameters should be lower and upper bounds

Note also that the OM has lengths of selectivity & retention >> length of maturity and very low discard mortality. Under these conditions, the stock may be almost invulnerable to high fishing mortality, and it may be difficult or impossible for the population dynamics model to reduce biomass down to low levels of depletion (the last part of the error you posted above).  

Let me know if you have any other issues. We'd love to learn more about your application of DLMtool to Chile fisheries.

**Comment by MauroMardones** [comment]
Phew!
Good advice to follow in this. You're right.

I am trying to propose MSE in Benthic Management Plan in Chile, I will start with the sea urchin. I'm in an internship and I will propose some MP from the library for these fishery and see their performance. At the end of September I will have a report and I will get it to you and if you can review and give me some feedback, it would be great for me.

Greetings and thanks again. I will be consulting you.

**Comment by MauroMardones** [comment]
Hi Adrian

allow me to ask again...

Do you know what mean this message?

_Running Historical Simulations
44 sims can't get down to the lower bound on depletion
3 sims can't get to the upper bound on depletion
Error in runMSE_int(OM, MPs, CheckMPs, timelimit, Hist, ntrials, fracD,  : 
  Change OM@seed and try again for a complete new sample, modify the input parameters, or increase ntrials_

regards

**Comment by AdrianHordyk** [comment]
This means the population dynamics model cannot generate simulations where the stock ends up at the specified depletion level. Assuming that the parameters in the OM are correct, this may be caused the issue I mention in previous post:

> Note also that the OM has lengths of selectivity & retention >> length of maturity and very low discard mortality. Under these conditions, the stock may be almost invulnerable to high fishing mortality, and it may be difficult or impossible for the population dynamics model to reduce biomass down to low levels of depletion (the last part of the error you posted above).

**Comment by MauroMardones** [comment]
Gracias Adrian!!
I've fixed it and now I have my MO walking.
now to the phase of incorporating my data!
let's move forward...

**Comment by AdrianHordyk** [comment]
Great to hear. I'll go ahead and close the issue.
