### ISSUE TITLE
When stocks go extinct

### ISSUE THREAD

**Issue by elisvb** [DLMtool/DLMtool#215]
I was wondering how DLMtool models stocks that go extinct (i.e. go below a minimal viable population size).  Can stocks pop back to life when at an extremely low biomass? Or are they considered 'doomed' below a certain threshold (e.g. when below x% of SSBmsy)? If so, how are they killed? Can the threshold be modified?

I am sorry if I this is written somewhere but I didn't see it.

**Comment by AdrianHordyk** [comment]
Currently, there is no minimal viable population size in the operating model. The population can recover from very low biomass if fishing pressure is completely removed.

We could look at adding this feature if it would be useful.

**Comment by elisvb** [comment]
Thank you! I mainly asked to understand the assumptions and results better.
