### ISSUE TITLE
setup() should export custom MPs (in globalenv) to cluster

### ISSUE THREAD

**Issue by quang-huynh** [DLMtool/DLMtool#216]
Additionally, run `sfLibrary(MSEtool)` if the package is in the search path.

**Comment by AdrianHordyk** [comment]
Custom MPs are exported to cluster already with `runMSE`.

Is `sfLibrary(MSEtool)` required - seems to work okay without?

**Comment by quang-huynh** [comment]
With MSEtool v-1.0.0, data-rich MPs are created by `make_MP`. Thus, the MP's binding environment is the global environment which is exported to the cluster. There's no issue here.

The next MSEtool patch will have pre-defined data-rich MPs whose binding environment is the MSEtool package namespace. These MPs, e.g. `SCA_MSY`, do not pass `runMSE` check:

```
Error in snowfall::sfExport(list = cMPs) : 
Unknown/unfound variable SCA_MSY in export. (local=TRUE)
```
or
```
Error: SCA_MSY is not a valid MP
```

**Comment by AdrianHordyk** [comment]
MSEtool is now exported if package has been loaded. Can you confirm it is working ok with dev version of MSEtool?

**Comment by quang-huynh** [comment]
Pre-defined MPs fail the check in line 93 of `runMSE` since this check only looks at DLMtool namespace and the global environment for MPs. Fix should be to test `MPs %in% ls('package:MSEtool')` in conjunction with `sfLibrary(MSEtool)` call.
