### ISSUE TITLE
CAL_bins may differ among cores when running MSE in parallel

### ISSUE THREAD

**Issue by quang-huynh** [DLMtool/DLMtool#217]
This happens in the Capelin OM in DLMextra.

**Comment by AdrianHordyk** [comment]
is there an error? Can't reproduce

**Comment by quang-huynh** [comment]
Here is the link to the Hist object, I had to edit runMSE to run Hist in parallel: https://www.dropbox.com/s/9qn0160g134i8fx/Hist.RData?dl=0 (load via readRDS)

```
setup(12)
Hist <- runMSE(DLMextra::Capelin_DFO_GSL, Hist = TRUE, parallel = TRUE)
Data <- lapply(Hist, getElement, "Data")
CAL_bins <- lapply(Data, slot, "CAL_bins")
```

**Comment by AdrianHordyk** [comment]
This isn't really a bug. Parallel processing is disabled for Hist=TRUE for this and other related reasons. 
It isn't a problem when running full MSE.
