### ISSUE TITLE
Add a Data2csv test script

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#232]
Eg:
dats<-avail('Data')
ndat<-length(dats)
file<-"C:/temp/tempdat.csv"
for(dd in 1:ndat)  Data2SS(get(dats[dd]), file, simno = 1,overwrite=T) 
for(dd in 1:ndat)  Data2SS(get(dats[dd]), file, simno = 1,overwrite=T, keepNAs=F)

**Comment by AdrianHordyk** [comment]
Added to tests
