### ISSUE TITLE
DLMextra() bug

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#234]
From a fresh R session this is what I get:

> library(DLMtool)
Loading required package: snowfall
Loading required package: snow
> DLMextra()

Downloading 'DLMextra' from GitHub
Error in if (tt) { : argument is not interpretable as logical

**Comment by AdrianHordyk** [comment]
This is caused by changes in the latest version of devtools. Issue has been fixed in the dev version of DLMtool
