### ISSUE TITLE
OMdoc plots should use calendar years for historical period

### ISSUE THREAD

**Issue by quang-huynh** [DLMtool/DLMtool#257]
As more OMs are developed for our library, historical time series would be more relatable if calendar years were used in time series plots. Currently, calendar years are used in EffLower and EffUpper tables but generic `1:OM@nyears` elsewhere.

Related, this may require updates in many more plotting functions, Data objects, etc.

**Comment by AdrianHordyk** [comment]
Fixed in new plot.OM
