### ISSUE TITLE
Problem with sampling Linf less than LFS and resulting V from SelectFun

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#26]
If the user specifies a length at full selection that is higher than Linf, clearly they have messed up. We need an error catch to diagnose this (or a workaround such as normalization to max vulnerability 1).

**Comment by AdrianHordyk** [comment]
We have this in runMSE [(around here)](https://github.com/DLMtool/DLMtool/blob/master/R/runMSE.r#L368-L372)
```
message("LFS too high (LFS > Linf) in some cases. \nDefaulting to LFS = 0.9 Linf for the affected simulations")
LFS[ind] <- Linf[ind[, 2]] * 0.9
```
Does that solve it?

**Comment by tcarruth** [comment]
Doesn't seem to happen early enough in the code to affect the selectivity curves
