### ISSUE TITLE
Demographic MPs using "Abun" slot

### ISSUE THREAD

**Issue by mingsun** [DLMtool/DLMtool#265]
As I carefully looked through some MPs using the demographic method, I realize that the Abun slot in class Data is not very consistently used among these MPs.

Say, for MP DynF, Abun is basically treated as "biomass" because the unit of output TAC was "ton". While in MP Fdem, the unit becomes "unitless" (I think this is the right one). When I looked into the code, I found DynF is constructing surplus production using abundance, so the result should actually be "unitless" as well since it is not real biomass.

Given "Abun" stand for abundance, not biomass, I feel that the output from DepF, DynF, and Fratio (and related MPs) have wrong units. The Fdem is fine.

**Comment by AdrianHordyk** [comment]
Abundance (`Data@Abun`) = current vulnerable biomass. The units for the TAC and Abun slots are specified manually in the Data object (`Data@Units`) and only used for plotting purposes.
