### ISSUE TITLE
Setting TAEFrac results in effort regulation and catch not reflecting TAC

### ISSUE THREAD

**Issue by seananderson** [DLMtool/DLMtool#267]
@robynforrest was getting some strange results with the Pacific cod OM. I dug into it and I think I've narrowed it down to this:

Minimal example:

```r
library(DLMtool)
om <- DLMtool::testOM
om@nsim <- 3
om2 <- om
om@TAEFrac <- c(1, 1)
om2@TAEFrac <- c(0.99999, 1)

mse <- runMSE(OM = om, MPs = "AvC")
mse2 <- runMSE(OM = om2, MPs = "AvC")

par(mfrow = c(2, 1))
plot(mse@B[1,,])
plot(mse2@B[1,,])

plot(mse@C[1,,])
plot(mse2@C[1,,])
```

Expected behaviour: output should be similar for `TAEFrac = 1` vs. `TAEFrac = 0.99999`.

Observed behaviour: projected biomass and catch are very different since `TAEFrac != 1` results in `Ei != 1` here: https://github.com/DLMtool/DLMtool/blob/acc730d27c0f67452452f722c4fe3a69548fc22f/R/popdyn.R#L78-L79

and therefore this effort-regulation code gets run: https://github.com/DLMtool/DLMtool/blob/acc730d27c0f67452452f722c4fe3a69548fc22f/R/popdyn.R#L403-L426

which overwrites `CB_P` and `CB_Pret` etc. for any iterations with `Effort > Ei`. That calculation of `FM_Pret` doesn't involve the recommended TAC and is based on the final historical year F and TAEFrac.

Now that I've written this out, I can see the logic there, but we certainly found it confusing that a TAEFrac that isn't 1 enables effort regulation based on historical effort that overrides a catch recommendation.

A potential second issue is that `Ftot` gets defined above based on `CB_P` but is not updated if `CB_P` gets updated in the effort code chunk. If I continue following `runMSE()`, I think `Ftot` gets returned as `FM` and gets used in the F/Fmsy calculation.

**Comment by seananderson** [comment]
Having thought more about it, I think the first issue is more of a user interface issue. I would find it helpful to get a warning if `TAEFrac` is causing a non-TAE MP to have its recommendation overruled. Or even more simply, if `TAEFrac` is set to anything but c(1, 1) for a TAC MP.  What if I wanted to compare TAE and TAC MPs with effort implementation error only on the effort MPs?

The second issue I mentioned at the end might be a bigger issue though. It means that if `TAEFrac` is set, then reported F and F/Fmsy will be incorrect for any TAC MPs if recommended catch results in an effort above a threshold.

**Comment by AdrianHordyk** [comment]
Yes, this isn't right - the TAE restriction should only occur if a TAE has been returned by an MP. Will look into both issues

**Comment by AdrianHordyk** [comment]
The most recent push to DLMtool master should fix this issue. The code to implement MP recommendations has been revised to include the development of a simple bioeconomic model. Ignore that for now, but it appears to have fixed both issues.

**Comment by robynforrest** [comment]
Quick fix much appreciated!

**Comment by seananderson** [comment]
Thanks! That fixes it.
