### ISSUE TITLE
Dealing with biennial or triennial surveys

### ISSUE THREAD

**Issue by seananderson** [DLMtool/DLMtool#270]
Most of our surveys are run every second year. The current MPs that rely on a survey index (or on length or age compositions, if we assume they come from a survey) are based on observations every year. For simple index-based MPs it would be pretty easy to modify existing MPs to only let them see even or odd years (as an example). This would be a bit more involved for other MPs such as the delay difference model. The other downside is that this would require copying and modifying a lot of MPs or writing a bunch of wrapper functions, perhaps via a function factory.

Is this the best way to go about it, is this functionality already baked in, or is there some slicker way this could work without totally overhauling the current MSE loop?

**Comment by AdrianHordyk** [comment]
There is no slick way to do this at the moment. I'm planning to add a feature to specify temporal (and perhaps spatial) observations. Another option may be to add observation processes by year to `cpars`. Will look into both these options.

**Comment by seananderson** [comment]
Thanks. We'll investigate whether we can build a function factory that strips out survey observations before returning the main MP function. Will partly depend on how various MPs behave with NAs, but we can edit those if needed. No need to complicate other parts of the package just for this.

**Comment by seananderson** [comment]
In case anyone stumbles on this later, this was our function factory solution:
https://github.com/pbs-assess/gfdlm/blob/8e878a8b06f14ba7d92f12766de73463f275359c/R/mp.R#L31-L44
