### ISSUE TITLE
Error with subscript out of bounds

### ISSUE THREAD

**Issue by MauroMardones** [DLMtool/DLMtool#276]
When i try to compile my OM i have this 

__Rendering markdown document as OM_Clam_XI.pdf

processing file: OM_Clam_XI.Rmd
  |..                                                               |   4%
  ordinary text without R code

  |.....                                                            |   7%
label: plot.M (with options) 
List of 2
 $ echo   : logi FALSE
 $ fig.asp: num 1.5

Quitting from lines 236-237 (OM_Clam_XI.Rmd) 
Error in Pars$Marray[, its] : subscript out of bound_s_

Can help me  please!?

**Comment by AdrianHordyk** [comment]
Difficult to determine the cause of this without a reproducible example. What function are you calling? `OMdoc`? 

Could be that `OM@nsim` is too low - should be > 3

**Comment by MauroMardones** [comment]
that was. Thank you
