### ISSUE TITLE
Error when using cpars$Data and run in parallel

### ISSUE THREAD

**Issue by tokami** [DLMtool/DLMtool#292]
When running MSE in parallel, the function `cparscheck` is used which causes an error if the element `cpars$Data` is used (function returns `logical(0)`, which is used in if clause in `run_parallel` in line 397 in Misc_Internal.R. Example provided below:

```
require(DLMtool)

testOM@cpars$Data <- new("Data")
testOM@cpars$Data@AddInd <- array(1, dim=c(1, testOM@nsim, testOM@nyears))

mse1 <- runMSE(testOM, "AvC", parallel = FALSE)

mse2 <- runMSE(testOM, "AvC", parallel = TRUE)
```

**Comment by quang-huynh** [comment]
I use the following dimensions:

`testOM@cpars$Data@AddInd <- array(1, dim=c(testOM@nsim, x, testOM@nyears))`

where `x` is whatever number of surveys you have.

**Comment by tokami** [comment]
Doesn't do the trick for me... Does the example above work for you with the different dimensions? I think this only changes how this data is being used in the MP, right?

I see the problem in `dims <- sapply(cpars, dim1check)` where 

```dim1check <- function(x) {
        if (class(x) == "numeric" | class(x) == "integer") 
            length(x)
        else dim(x)[1]
    }
```
If `cpars` only includes a Data class object this function returns nothing. 

Adding a dummy vector with the right dimensions fixes the error.

**Comment by tokami** [comment]
Thus, this example works:

```
require(DLMtool)

testOM@cpars$Data <- new("Data")
testOM@cpars$Data@AddInd <- array(1, dim=c(1, testOM@nsim, testOM@nyears))
testOM@cpars$dummy = rep(0, testOM@nsim)

mse2 <- runMSE(testOM, "AvC", parallel = TRUE)
```
