### ISSUE TITLE
Extreme hyperstability values in Data@AddInd

### ISSUE THREAD

**Issue by quang-huynh** [DLMtool/DLMtool#293]
`DLMtool:::indfit` is currently generating extreme values of hyperstability. Here's quick example:

```
set.seed(43)
sim.index <- rep(1, 20)
obs.ind <- rlnorm(20, -0.5 * 0.1^2, 0.1)

opt<-optimize(DLMtool:::getbeta,x=sim.index,y=obs.ind,interval=c(0.1,10))
opt$minimum # beta = 10!
plot(obs.ind, typ = 'o')
lines(sim.index, col = 'red')

DLMtool:::indfit(sim.index, obs.ind, 1:20, TRUE) # beta = 10!
```

**Comment by AdrianHordyk** [comment]
This will happen if all sim.index == 1. 1^beta = 1. Does it occur under other conditions as well?

**Comment by AdrianHordyk** [comment]
Added msg to inspect Misc@ErrList for calculated error and beta values. Can now be over-ridden with cpars. 

Closing - re-open if it is still an issue
