### ISSUE TITLE
Keep CurrentYr in OM slot of MSE object

### ISSUE THREAD

**Issue by seananderson** [DLMtool/DLMtool#294]
It would be helpful if the `CurrentYr` slot could be maintained in the operating model component of an MSE Object. Otherwise, custom MSE plotting functions need an argument for the current year and it's easy to specify a number that doesn't match the original value. Unless I'm missing something and the value is already accessible in the MSE Object?

Example current behaviour:

``` r
library(DLMtool)
testOM@CurrentYr
#> [1] 50
testOM@nsim <- 2
m <- runMSE(testOM)
m@OM$CurrentYr
#> NULL
```

Expected behaviour:

```r
m@OM$CurrentYr
#> [1] 50
```

**Comment by AdrianHordyk** [comment]
Good point, will push a fix. `m@OM$CurrentYr` will be vector length `nsim` with `OM@CurrentYr`
