### ISSUE TITLE
Can Sub also subset @Misc$Data?

### ISSUE THREAD

**Issue by seananderson** [DLMtool/DLMtool#295]
Can `Sub()` also subset `@Misc$Data`? It looks like it currently does not:

``` r
library(DLMtool)
om <- testOM
om@nsim <- 2
m <- runMSE(om)

m@nMPs
#> [1] 6
m@MPs
#> [1] "AvC"       "DCAC"      "FMSYref"   "curE"      "matlenlim" "MRreal"
length(m@Misc$Data)
#> [1] 6

mSub <- Sub(m, MPs = "AvC")
mSub@nMPs
#> [1] 1
mSub@MPs
#> [1] "AvC"
length(mSub@Misc$Data)
#> [1] 6
```

Expected behaviour:

```r
length(mSub@Misc$Data)
#> [1] 1
```

If this is a pain then there may be some other way around this. Once the MSE object has been subsetted, I'm not sure how to easily figure out which elements of `@Misc$Data` match the rest of the MSE object. If there is some easy way to match them after the fact then I'm happy to do that in my own code.

**Comment by quang-huynh** [comment]
In the mean time, the simplest way to go about this would probably be:

```
mse@Misc$Data <- mse@Misc$Data[match(MP_subset, mse@MPs)]
Sub(mse, MP_subset)
```

**Comment by seananderson** [comment]
Thanks @quang-huynh, that works well for now. I was so caught up in the problem I didn't think about subsetting the data element *first*. Ha.
