### ISSUE TITLE
summary(Data) crashes when SpInd and VInd are empty slots

### ISSUE THREAD

**Issue by quang-huynh** [DLMtool/DLMtool#301]

**Comment by AdrianHordyk** [comment]
Give you provide an example Data file - the built-in Data objects work ok: `summary(Atlantic_mackerel, wait=FALSE)`

**Comment by quang-huynh** [comment]
Mysteriously the problem has disappeared for multiMSE https://github.com/tcarruth/MSEtool/commit/f912d6ce0af3232c6d0042336562c1e3975d65e2
