### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#310]
- plusgroup of cpars needs documenting
- explain exact derivation of cpars$D and D (inside runMSE) so users can match this up

**Comment by quang-huynh** [comment]
Currently, OM@cpars$plusgroup <- 1 turns on maxage as the plusgroup. Perhaps this should be the default going forward in the next major release?

**Comment by AdrianHordyk** [comment]
Definition of depletion and description of how it is calculated is in userguide Appendix D5

Default assumption will be to use plusgroup in upcoming V6.0
