### ISSUE TITLE
Additional Index slots only allow for a single spawning biomass index

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#311]
Need to make these nind dimensions to allow for multiple spawning biomass indices

Also

Need spawning numbers  with nind dimensions to allow for multiple spawning number indices

Also 

Both of these need optional vulnerability vectors as a surprisingly large number of fisheries seem to target spawning aggregations with additional vulnerability at age 

Total PITA - sorry!

**Comment by AdrianHordyk** [comment]
Added extra (optional) slots for Additional Indices (`Data@AddInd`)

`Data@AddIndType`  numeric vector length n.ind 1=total stock (default), 2=spawning stock, 3=vulnerable stock

`Data@AddIunits` numeric vector length n.ind 1=biomass (default) 0=numbers

**Comment by quang-huynh** [comment]
Is `cpars$AddIunits` no longer used?

When is custom selectivity `Data@AddIndV` used and how could you override `Data@AddIndType`?

**Comment by AdrianHordyk** [comment]
`cpars$AddIunits` is redundant now but still works for backwards compatibility. It'll be removed at some point

`Data@AddIndV` is used as previously, and by default is applied to total stock. `AddIndType` is optional & allows users to specify additional selectivity-at-age to spawning or vulnerable biomass.
