### ISSUE TITLE
Dynamic B0 reference point

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#322]
Temporal changes in operating model parameters can lead to radically different future projections of biomass - we have NFref but this doesn't reconstruct historical biomass assuming unfished conditions. 

This is primarily submitted because the lead analyst is clearly bored and needs something to do on a Friday night. You're welcome.

**Comment by quang-huynh** [comment]
For the time being, this can be added to the `MSEtool::SRA_scope` markdown report

**Comment by AdrianHordyk** [comment]
Dynamics B0, SB0, N0 etc are already returned in `MSE@Misc$Unfished$ByYear`
