### ISSUE TITLE
Fix plus group calculations 

### ISSUE THREAD

**Issue by AdrianHordyk** [DLMtool/DLMtool#329]
if(plusgroup){ # additionally, if plusgroup
surv[maxage]<-surv[maxage]+surv[maxage]*exp(-Maa[maxage])/(1-exp(-Maa[maxage])) # indefinite integral
}

**Comment by tcarruth** [comment]
Just to note I've now confirmed this in the VPA2OM - if I include the expected mismatch, I get perfect reconstruction of the VPA numbers at age using hist=T.

**Comment by AdrianHordyk** [comment]
Fixed in V6

**Comment by AdrianHordyk** [comment]
need to fix in MSY calcs still
