### ISSUE TITLE
New 'blank' OM object required 

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#36]
A blank OM object is needed with default settings for zero future gradients in M K etc

Either set up new('OM') so that it does not require defined stock, fleet, observation objects  

or

create a new template OM that is loaded at startup that default settings

**Comment by AdrianHordyk** [comment]
Done. new('OM') now returns a blank OM object if Stock=NULL. Mgrad, Msd, etc are all set to 0 using makePerf() function
