### ISSUE TITLE
Erroneous histograms produced by plot.Stock plot.Fleet plot.Obs plot.Imp when range is 0 

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#46]
Wide and erroneous single bar of a histogram is produced when plotting a Stock object slot with no range: 

e.g. Stock@M = c(0.2, 0.2)

**Comment by AdrianHordyk** [comment]
Fixed. Made a wrapper 'hist2' that plots a vertical line for data with no range
