### ISSUE TITLE
Variable Data - MP lag: 

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#47]
Right now DLMtool sets management advice in time t using data up to and including t-1. This should be variable. The easiest way to do this is via TAC <- TAC calculation where pseudocode is

TAC[t+lag]<- TAC(Data, MPs)

The only snag is that the current TAC needs filling for the first lag years using for example historical catches 

This isn't perfect but it is easy!

The other appach is more complex and required a Data object with variable year indexing, gah. This is more correct but will lead to all kinds of hell when for example lag>nyears etc etc.

**Comment by AdrianHordyk** [comment]
Decided at this stage data lags should be specified within custom MPs
