### ISSUE TITLE
plot.OM unrealistic F in historical simulations

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#65]
For some specific stock types and conditions, there are cases where the fishing mortality rate plateaus at some notional maximum F for a stable period of time in the historical simulations. This is not solvable by the maxF argument to runMSE (that is for projections only).

What is causing this behaviour and how can it be adjustable, ie higher historical Fs?

**Comment by AdrianHordyk** [comment]
Can't reproduce
