### ISSUE TITLE
Automatic time-step shortening or operating models and data objects

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#67]
OM <- OMshort(OM,4) # for a quarterly model
Data <- OMshort(Data,2) # for a biannual model

Parameters that need changing: k, M, FMSY, catches

**Comment by AdrianHordyk** [comment]
also recruitment, sampling of data, management interval. Great idea but not a quick fix!

**Comment by AdrianHordyk** [comment]
To be done at a later stage
