### ISSUE TITLE
MSE@F_FMSY na scores possible. No idea how

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#71]
Found this for Rougheye operating model that can create NA scores in MSEobj@F_FMSY given DDes MP

**Comment by AdrianHordyk** [comment]
Should be fixed now. when MP returns NA as TAC recommendation, the TAC from last time-step is used. This avoids NA is catch which results in NA values in F.

**Comment by tcarruth** [comment]
Ok lets close it.
