### ISSUE TITLE
Error in the population of the first simulated data object AND the dreaded CAL error

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#78]
Error 1:
"Calculating historical stock and fishing dynamics
Calculating MSY reference points
Calculating reference yield - best fixed F strategy
Error in Data@L95[Data@L95 > 0.9 * Data@vbLinf] <- 0.9 * Data@vbLinf[Data@L95 >  : 
  NAs are not allowed in subscripted assignments
"

- The issue arises from prescribing an operating model with OM@L50_95 that is too large

Error 2:
"There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In min(which(round(CAL[i, nyears, ], 0) > 1)) :
  no non-missing arguments to min; returning Inf
2: In min(which(round(CAL[i, interval, ], 0) > 1)) :
  no non-missing arguments to min; returning Inf
3: In min(which(round(CAL[i, interval, ], 0) > 1)) :
"

- Presumably relating to nCAA or nCAL.

=== Reproducible by the generic MSC run (you have the files Adrian) =====

library('DLMtool')
setup()

setwd("C:/MSC_prelim")
source("Source.R")

GenericOM<-OM_xl("OMGeneric.xlsx","Generic")
Ms<-c(0.03,0.05,0.1,0.2,0.4,0.8)
nblocks<-length(Ms)-1

nsim<-500
GenericOM@nsim<-nsim

# MPs
MPs<-c(avail('Output'),avail('Input'))
cond<-!grepl("_ML",MPs)&!grepl("_CC",MPs)&!grepl("CompSRA",MPs)&!grepl("LBSPR",MPs)
MPs<-MPs[cond]

j<-2
 
  simtest<-nsim*2
  GenericOM@M<-c(Ms[j],Ms[j+1])
  M<-runif(simtest,Ms[j],Ms[j+1])
  maxage<-ceiling(-log(0.01)/Ms[j])
  GenericOM@maxage<-maxage
  
  Mline<-seq(Ms[j],Ms[j+1],length.out=nsim)
  calcMatK(MMatKfile="MMatK.csv",Mpoints=M,Mline,ploty=F,"demographics.jpg")  # calculate age at 50% maturity and vonB K parameter from natural mortality rate
  
  par(mfrow=c(1,2))
  hist(M/K,breaks=20)
  cond<-(M/K)>0.3 & (M/K)<4 & ageM<0.75*maxage
  
  M<-M[cond][1:nsim]
  K<-K[cond][1:nsim]
  hist(M/K,breaks=20)
  ageM<-ageM[cond][1:nsim]
  t0<-runif(nsim,GenericOM@t0[1],GenericOM@t0[2])
  Linf<-runif(nsim,GenericOM@Linf[1],GenericOM@Linf[2])
  
  
  # == Generate Maturity-at-Age array ====
  
  ageMsd<-runif(nsim,0.05,0.3) # This is what is causing the issue - change 0.3 to 0.4 it happens more often
  ageMarray <- array(ageM, dim = c(nsim, GenericOM@maxage)) 
  Agearray<-array(rep(1:GenericOM@maxage,each=nsim),dim(ageMarray))# Age at maturity array
  Mat_age <- 1/(1 + exp((ageMarray - (Agearray))/(ageMarray * ageMsd)))  # Maturity at age array
  
  L50 <- Linf*(1-exp(-K*(ageM-t0)))
  A95 <--((ageM*ageMsd)*log((1/0.95)-1)-ageM)
  L95 <-Linf*(1-exp(-K*(A95-t0)))
  L50_95<-L95-L50
  
  
  # == Fishing trajectories =====
  ny<-GenericOM@nyears
  Eslp<-runif(nsim,-5,5)
  E<-array(NA,c(nsim,ny))
  bh<-floor(ny/2)
  for(i in 1:nsim)E[i,1:floor(ny/2)]<-seq(0,1,length.out=bh+1)[2:(bh+1)]
  for(i in 1:nsim)E[i,(bh+1):ny]<-(1+Eslp[i]/100)^(1:(ny-bh))
  Find<-E/mean(E)
  dFfinal<-Eslp 
 
  
  # == Populate cpars ==========================
  
  GenericOM@cpars$ageM<-ageM
  GenericOM@cpars$age95<-A95
  GenericOM@cpars$Mat_age<-Mat_age
  GenericOM@cpars$L50<-L50
  GenericOM@cpars$L50_95<-L50_95
  GenericOM@cpars$Find<-Find
  GenericOM@cpars$dFfinal<-dFfinal
  
  # run the MSE
  test<-runMSErobust(GenericOM,MPs=MPs)
  
  # debugging
  Stock<-GenericOM
  cpars<-GenericOM@cpars
  save(test,file=paste("test",j))

**Comment by AdrianHordyk** [comment]
fixed!
