### ISSUE TITLE
Missing slots in example data

### ISSUE THREAD

**Issue by seananderson** [DLMtool/DLMtool#92]
It looks like the example data sets are missing `LenCV` and `nareas` slots. This means that a variety of functions such as `Can()`, `TAC()`, etc. can't be run on them. I think this is both in the .rdata and .csv files. I assume these slots were added more recently than these data objects were created. 

```r
library(DLMtool)
Example_datafile
#> ...
#> Error in slot(object, what) : 
#>   no slot of name "LenCV" for this object of class "Data"

Example_datafile@LenCV <- 0.1
Example_datafile
#> ...
#> Error in slot(object, what) : 
#>   no slot of name "nareas" for this object of class "Data"
```

It also looks like the example stock object `Blue_shark` is missing some slots. 

```r
Blue_shark
#> Slot "M2":
#> Error in slot(object, what) : 
#>  no slot of name "M2" for this object of class "Stock"
```

**Comment by AdrianHordyk** [comment]
Now fixed in the development version. Updated version with fix to be released on CRAN shortly. In the meantime, need to use the workaround you mention: e.g Example_datafile@nareas <- 2
